4.3.0 2025-07-01 01:40:54,926 INFO 31696 - Starting to get apps
4.3.0 2025-07-01 01:40:55,220 ERROR 31696 - Could not make request to Splunk: [HTTP 401] Client is not authenticated
Traceback (most recent call last):
  File "C:\Program Files\Splunk\etc\apps\python_upgrade_readiness_app\bin\eura_scan_apps.py", line 48, in get_all_apps
    response, content = sr.simpleRequest(path=endpoint, sessionKey=session_key, method="GET")
  File "C:\Program Files\Splunk\Python-3.7\lib\site-packages\splunk\rest\__init__.py", line 643, in simpleRequest
    raise splunk.AuthenticationFailed
splunk.AuthenticationFailed: [HTTP 401] Client is not authenticated
4.3.0 2025-07-01 01:40:55,225 INFO 31696 - Starting to trigger scan
4.3.0 2025-07-01 01:40:55,240 ERROR 31696 - Could not make request to Splunk: [HTTP 401] Client is not authenticated
Traceback (most recent call last):
  File "C:\Program Files\Splunk\etc\apps\python_upgrade_readiness_app\bin\eura_scan_apps.py", line 77, in trigger_scan
    jsonargs=json.dumps(body))
  File "C:\Program Files\Splunk\Python-3.7\lib\site-packages\splunk\rest\__init__.py", line 643, in simpleRequest
    raise splunk.AuthenticationFailed
splunk.AuthenticationFailed: [HTTP 401] Client is not authenticated
4.3.0 2025-07-02 02:53:28,122 INFO 67992 - Starting to get apps
4.3.0 2025-07-02 02:53:28,394 ERROR 67992 - Could not make request to Splunk: [HTTP 401] Client is not authenticated
Traceback (most recent call last):
  File "C:\Program Files\Splunk\etc\apps\python_upgrade_readiness_app\bin\eura_scan_apps.py", line 48, in get_all_apps
    response, content = sr.simpleRequest(path=endpoint, sessionKey=session_key, method="GET")
  File "C:\Program Files\Splunk\Python-3.7\lib\site-packages\splunk\rest\__init__.py", line 643, in simpleRequest
    raise splunk.AuthenticationFailed
splunk.AuthenticationFailed: [HTTP 401] Client is not authenticated
4.3.0 2025-07-02 02:53:28,396 INFO 67992 - Starting to trigger scan
4.3.0 2025-07-02 02:53:28,423 ERROR 67992 - Could not make request to Splunk: [HTTP 401] Client is not authenticated
Traceback (most recent call last):
  File "C:\Program Files\Splunk\etc\apps\python_upgrade_readiness_app\bin\eura_scan_apps.py", line 77, in trigger_scan
    jsonargs=json.dumps(body))
  File "C:\Program Files\Splunk\Python-3.7\lib\site-packages\splunk\rest\__init__.py", line 643, in simpleRequest
    raise splunk.AuthenticationFailed
splunk.AuthenticationFailed: [HTTP 401] Client is not authenticated
4.3.0 2025-07-03 02:38:45,166 INFO 102344 - Starting to get apps
4.3.0 2025-07-03 02:38:45,484 ERROR 102344 - Could not make request to Splunk: [HTTP 401] Client is not authenticated
Traceback (most recent call last):
  File "C:\Program Files\Splunk\etc\apps\python_upgrade_readiness_app\bin\eura_scan_apps.py", line 48, in get_all_apps
    response, content = sr.simpleRequest(path=endpoint, sessionKey=session_key, method="GET")
  File "C:\Program Files\Splunk\Python-3.7\lib\site-packages\splunk\rest\__init__.py", line 643, in simpleRequest
    raise splunk.AuthenticationFailed
splunk.AuthenticationFailed: [HTTP 401] Client is not authenticated
4.3.0 2025-07-03 02:38:45,484 INFO 102344 - Starting to trigger scan
4.3.0 2025-07-03 02:38:45,514 ERROR 102344 - Could not make request to Splunk: [HTTP 401] Client is not authenticated
Traceback (most recent call last):
  File "C:\Program Files\Splunk\etc\apps\python_upgrade_readiness_app\bin\eura_scan_apps.py", line 77, in trigger_scan
    jsonargs=json.dumps(body))
  File "C:\Program Files\Splunk\Python-3.7\lib\site-packages\splunk\rest\__init__.py", line 643, in simpleRequest
    raise splunk.AuthenticationFailed
splunk.AuthenticationFailed: [HTTP 401] Client is not authenticated
4.3.0 2025-07-06 17:20:53,444 INFO 108892 - Starting to get apps
4.3.0 2025-07-06 17:20:53,825 ERROR 108892 - Could not make request to Splunk: [HTTP 401] Client is not authenticated
Traceback (most recent call last):
  File "C:\Program Files\Splunk\etc\apps\python_upgrade_readiness_app\bin\eura_scan_apps.py", line 48, in get_all_apps
    response, content = sr.simpleRequest(path=endpoint, sessionKey=session_key, method="GET")
  File "C:\Program Files\Splunk\Python-3.7\lib\site-packages\splunk\rest\__init__.py", line 643, in simpleRequest
    raise splunk.AuthenticationFailed
splunk.AuthenticationFailed: [HTTP 401] Client is not authenticated
4.3.0 2025-07-06 17:20:53,828 INFO 108892 - Starting to trigger scan
4.3.0 2025-07-06 17:20:53,872 ERROR 108892 - Could not make request to Splunk: [HTTP 401] Client is not authenticated
Traceback (most recent call last):
  File "C:\Program Files\Splunk\etc\apps\python_upgrade_readiness_app\bin\eura_scan_apps.py", line 77, in trigger_scan
    jsonargs=json.dumps(body))
  File "C:\Program Files\Splunk\Python-3.7\lib\site-packages\splunk\rest\__init__.py", line 643, in simpleRequest
    raise splunk.AuthenticationFailed
splunk.AuthenticationFailed: [HTTP 401] Client is not authenticated
4.3.0 2025-07-07 01:00:01,878 INFO 121012 - Starting to get apps
4.3.0 2025-07-07 01:00:02,137 ERROR 121012 - Could not make request to Splunk: [HTTP 401] Client is not authenticated
Traceback (most recent call last):
  File "C:\Program Files\Splunk\etc\apps\python_upgrade_readiness_app\bin\eura_scan_apps.py", line 48, in get_all_apps
    response, content = sr.simpleRequest(path=endpoint, sessionKey=session_key, method="GET")
  File "C:\Program Files\Splunk\Python-3.7\lib\site-packages\splunk\rest\__init__.py", line 643, in simpleRequest
    raise splunk.AuthenticationFailed
splunk.AuthenticationFailed: [HTTP 401] Client is not authenticated
4.3.0 2025-07-07 01:00:02,141 INFO 121012 - Starting to trigger scan
4.3.0 2025-07-07 01:00:02,168 ERROR 121012 - Could not make request to Splunk: [HTTP 401] Client is not authenticated
Traceback (most recent call last):
  File "C:\Program Files\Splunk\etc\apps\python_upgrade_readiness_app\bin\eura_scan_apps.py", line 77, in trigger_scan
    jsonargs=json.dumps(body))
  File "C:\Program Files\Splunk\Python-3.7\lib\site-packages\splunk\rest\__init__.py", line 643, in simpleRequest
    raise splunk.AuthenticationFailed
splunk.AuthenticationFailed: [HTTP 401] Client is not authenticated
4.3.0 2025-07-08 01:00:02,862 INFO 148200 - Starting to get apps
4.3.0 2025-07-08 01:00:03,251 ERROR 148200 - Could not make request to Splunk: [HTTP 401] Client is not authenticated
Traceback (most recent call last):
  File "C:\Program Files\Splunk\etc\apps\python_upgrade_readiness_app\bin\eura_scan_apps.py", line 48, in get_all_apps
    response, content = sr.simpleRequest(path=endpoint, sessionKey=session_key, method="GET")
  File "C:\Program Files\Splunk\Python-3.7\lib\site-packages\splunk\rest\__init__.py", line 643, in simpleRequest
    raise splunk.AuthenticationFailed
splunk.AuthenticationFailed: [HTTP 401] Client is not authenticated
4.3.0 2025-07-08 01:00:03,254 INFO 148200 - Starting to trigger scan
4.3.0 2025-07-08 01:00:03,271 ERROR 148200 - Could not make request to Splunk: [HTTP 401] Client is not authenticated
Traceback (most recent call last):
  File "C:\Program Files\Splunk\etc\apps\python_upgrade_readiness_app\bin\eura_scan_apps.py", line 77, in trigger_scan
    jsonargs=json.dumps(body))
  File "C:\Program Files\Splunk\Python-3.7\lib\site-packages\splunk\rest\__init__.py", line 643, in simpleRequest
    raise splunk.AuthenticationFailed
splunk.AuthenticationFailed: [HTTP 401] Client is not authenticated
4.3.0 2025-07-09 01:00:02,873 INFO 157400 - Starting to get apps
4.3.0 2025-07-09 01:00:03,217 ERROR 157400 - Could not make request to Splunk: [HTTP 401] Client is not authenticated
Traceback (most recent call last):
  File "C:\Program Files\Splunk\etc\apps\python_upgrade_readiness_app\bin\eura_scan_apps.py", line 48, in get_all_apps
    response, content = sr.simpleRequest(path=endpoint, sessionKey=session_key, method="GET")
  File "C:\Program Files\Splunk\Python-3.7\lib\site-packages\splunk\rest\__init__.py", line 643, in simpleRequest
    raise splunk.AuthenticationFailed
splunk.AuthenticationFailed: [HTTP 401] Client is not authenticated
4.3.0 2025-07-09 01:00:03,219 INFO 157400 - Starting to trigger scan
4.3.0 2025-07-09 01:00:03,244 ERROR 157400 - Could not make request to Splunk: [HTTP 401] Client is not authenticated
Traceback (most recent call last):
  File "C:\Program Files\Splunk\etc\apps\python_upgrade_readiness_app\bin\eura_scan_apps.py", line 77, in trigger_scan
    jsonargs=json.dumps(body))
  File "C:\Program Files\Splunk\Python-3.7\lib\site-packages\splunk\rest\__init__.py", line 643, in simpleRequest
    raise splunk.AuthenticationFailed
splunk.AuthenticationFailed: [HTTP 401] Client is not authenticated
4.3.0 2025-07-10 00:59:43,119 INFO 186236 - Starting to get apps
4.3.0 2025-07-10 00:59:43,406 ERROR 186236 - Could not make request to Splunk: [HTTP 401] Client is not authenticated
Traceback (most recent call last):
  File "C:\Program Files\Splunk\etc\apps\python_upgrade_readiness_app\bin\eura_scan_apps.py", line 48, in get_all_apps
    response, content = sr.simpleRequest(path=endpoint, sessionKey=session_key, method="GET")
  File "C:\Program Files\Splunk\Python-3.7\lib\site-packages\splunk\rest\__init__.py", line 643, in simpleRequest
    raise splunk.AuthenticationFailed
splunk.AuthenticationFailed: [HTTP 401] Client is not authenticated
4.3.0 2025-07-10 00:59:43,409 INFO 186236 - Starting to trigger scan
4.3.0 2025-07-10 00:59:43,450 ERROR 186236 - Could not make request to Splunk: [HTTP 401] Client is not authenticated
Traceback (most recent call last):
  File "C:\Program Files\Splunk\etc\apps\python_upgrade_readiness_app\bin\eura_scan_apps.py", line 77, in trigger_scan
    jsonargs=json.dumps(body))
  File "C:\Program Files\Splunk\Python-3.7\lib\site-packages\splunk\rest\__init__.py", line 643, in simpleRequest
    raise splunk.AuthenticationFailed
splunk.AuthenticationFailed: [HTTP 401] Client is not authenticated
4.3.0 2025-07-10 01:00:01,090 INFO 192872 - Starting to get apps
4.3.0 2025-07-10 01:00:01,440 ERROR 192872 - Could not make request to Splunk: [HTTP 401] Client is not authenticated
Traceback (most recent call last):
  File "C:\Program Files\Splunk\etc\apps\python_upgrade_readiness_app\bin\eura_scan_apps.py", line 48, in get_all_apps
    response, content = sr.simpleRequest(path=endpoint, sessionKey=session_key, method="GET")
  File "C:\Program Files\Splunk\Python-3.7\lib\site-packages\splunk\rest\__init__.py", line 643, in simpleRequest
    raise splunk.AuthenticationFailed
splunk.AuthenticationFailed: [HTTP 401] Client is not authenticated
4.3.0 2025-07-10 01:00:01,442 INFO 192872 - Starting to trigger scan
4.3.0 2025-07-10 01:00:01,456 ERROR 192872 - Could not make request to Splunk: [HTTP 401] Client is not authenticated
Traceback (most recent call last):
  File "C:\Program Files\Splunk\etc\apps\python_upgrade_readiness_app\bin\eura_scan_apps.py", line 77, in trigger_scan
    jsonargs=json.dumps(body))
  File "C:\Program Files\Splunk\Python-3.7\lib\site-packages\splunk\rest\__init__.py", line 643, in simpleRequest
    raise splunk.AuthenticationFailed
splunk.AuthenticationFailed: [HTTP 401] Client is not authenticated
4.3.0 2025-07-11 01:00:02,820 INFO 212788 - Starting to get apps
4.3.0 2025-07-11 01:00:03,151 ERROR 212788 - Could not make request to Splunk: [HTTP 401] Client is not authenticated
Traceback (most recent call last):
  File "C:\Program Files\Splunk\etc\apps\python_upgrade_readiness_app\bin\eura_scan_apps.py", line 48, in get_all_apps
    response, content = sr.simpleRequest(path=endpoint, sessionKey=session_key, method="GET")
  File "C:\Program Files\Splunk\Python-3.7\lib\site-packages\splunk\rest\__init__.py", line 643, in simpleRequest
    raise splunk.AuthenticationFailed
splunk.AuthenticationFailed: [HTTP 401] Client is not authenticated
4.3.0 2025-07-11 01:00:03,152 INFO 212788 - Starting to trigger scan
4.3.0 2025-07-11 01:00:03,165 ERROR 212788 - Could not make request to Splunk: [HTTP 401] Client is not authenticated
Traceback (most recent call last):
  File "C:\Program Files\Splunk\etc\apps\python_upgrade_readiness_app\bin\eura_scan_apps.py", line 77, in trigger_scan
    jsonargs=json.dumps(body))
  File "C:\Program Files\Splunk\Python-3.7\lib\site-packages\splunk\rest\__init__.py", line 643, in simpleRequest
    raise splunk.AuthenticationFailed
splunk.AuthenticationFailed: [HTTP 401] Client is not authenticated
4.3.0 2025-07-12 01:00:03,005 INFO 237852 - Starting to get apps
4.3.0 2025-07-12 01:00:03,331 ERROR 237852 - Could not make request to Splunk: [HTTP 401] Client is not authenticated
Traceback (most recent call last):
  File "C:\Program Files\Splunk\etc\apps\python_upgrade_readiness_app\bin\eura_scan_apps.py", line 48, in get_all_apps
    response, content = sr.simpleRequest(path=endpoint, sessionKey=session_key, method="GET")
  File "C:\Program Files\Splunk\Python-3.7\lib\site-packages\splunk\rest\__init__.py", line 643, in simpleRequest
    raise splunk.AuthenticationFailed
splunk.AuthenticationFailed: [HTTP 401] Client is not authenticated
4.3.0 2025-07-12 01:00:03,333 INFO 237852 - Starting to trigger scan
4.3.0 2025-07-12 01:00:03,362 ERROR 237852 - Could not make request to Splunk: [HTTP 401] Client is not authenticated
Traceback (most recent call last):
  File "C:\Program Files\Splunk\etc\apps\python_upgrade_readiness_app\bin\eura_scan_apps.py", line 77, in trigger_scan
    jsonargs=json.dumps(body))
  File "C:\Program Files\Splunk\Python-3.7\lib\site-packages\splunk\rest\__init__.py", line 643, in simpleRequest
    raise splunk.AuthenticationFailed
splunk.AuthenticationFailed: [HTTP 401] Client is not authenticated
4.3.0 2025-07-13 01:00:02,775 INFO 254664 - Starting to get apps
4.3.0 2025-07-13 01:00:03,110 ERROR 254664 - Could not make request to Splunk: [HTTP 401] Client is not authenticated
Traceback (most recent call last):
  File "C:\Program Files\Splunk\etc\apps\python_upgrade_readiness_app\bin\eura_scan_apps.py", line 48, in get_all_apps
    response, content = sr.simpleRequest(path=endpoint, sessionKey=session_key, method="GET")
  File "C:\Program Files\Splunk\Python-3.7\lib\site-packages\splunk\rest\__init__.py", line 643, in simpleRequest
    raise splunk.AuthenticationFailed
splunk.AuthenticationFailed: [HTTP 401] Client is not authenticated
4.3.0 2025-07-13 01:00:03,113 INFO 254664 - Starting to trigger scan
4.3.0 2025-07-13 01:00:03,127 ERROR 254664 - Could not make request to Splunk: [HTTP 401] Client is not authenticated
Traceback (most recent call last):
  File "C:\Program Files\Splunk\etc\apps\python_upgrade_readiness_app\bin\eura_scan_apps.py", line 77, in trigger_scan
    jsonargs=json.dumps(body))
  File "C:\Program Files\Splunk\Python-3.7\lib\site-packages\splunk\rest\__init__.py", line 643, in simpleRequest
    raise splunk.AuthenticationFailed
splunk.AuthenticationFailed: [HTTP 401] Client is not authenticated
4.3.0 2025-07-14 01:00:03,423 INFO 275916 - Starting to get apps
4.3.0 2025-07-14 01:00:03,708 ERROR 275916 - Could not make request to Splunk: [HTTP 401] Client is not authenticated
Traceback (most recent call last):
  File "C:\Program Files\Splunk\etc\apps\python_upgrade_readiness_app\bin\eura_scan_apps.py", line 48, in get_all_apps
    response, content = sr.simpleRequest(path=endpoint, sessionKey=session_key, method="GET")
  File "C:\Program Files\Splunk\Python-3.7\lib\site-packages\splunk\rest\__init__.py", line 643, in simpleRequest
    raise splunk.AuthenticationFailed
splunk.AuthenticationFailed: [HTTP 401] Client is not authenticated
4.3.0 2025-07-14 01:00:03,711 INFO 275916 - Starting to trigger scan
4.3.0 2025-07-14 01:00:03,738 ERROR 275916 - Could not make request to Splunk: [HTTP 401] Client is not authenticated
Traceback (most recent call last):
  File "C:\Program Files\Splunk\etc\apps\python_upgrade_readiness_app\bin\eura_scan_apps.py", line 77, in trigger_scan
    jsonargs=json.dumps(body))
  File "C:\Program Files\Splunk\Python-3.7\lib\site-packages\splunk\rest\__init__.py", line 643, in simpleRequest
    raise splunk.AuthenticationFailed
splunk.AuthenticationFailed: [HTTP 401] Client is not authenticated
